### ISSUE TITLE
Limit and Skip don't work.

### ISSUE THREAD

**Issue by muliyul** [baugarten/node-restful#118]
Current mongodb version: 3.2.0
The previous version that worked: 3.0.8

After calling this endpoint:
http://localhost/api/events?limit=20&skip=0
I get the following error:
{
  "name": "MongoError",
  "message": "Failed to parse: { find: \"events\", filter: {}, skip: \"0\", limit: \"20\" }. 'skip' field must be numeric.",
  "waitedMS": 0,
  "ok": 0,
  "errmsg": "Failed to parse: { find: \"events\", filter: {}, skip: \"0\", limit: \"20\" }. 'skip' field must be numeric.",
  "code": 9
}

prob. missing a parseInt because mongodb changed something internally.

**Comment by baugarten** [comment]
I think this is fixed in 72c298d153a430f2d03f849a33828e3633093f02, released as version 0.2.5

Let me know if you have any trouble

**Comment by muliyul** [comment]
That did not work. I made sure I upgraded to 0.2.5

**Comment by karvapallo** [comment]
This has not been fixed and is still an issue. I have the exact same issue with version 0.2.5

**Comment by karvapallo** [comment]
Okay I think I found the bug in `model.js` line `458`:
https://github.com/baugarten/node-restful/blob/master/lib/model.js#L458

This is the current code:

```js
if (props[key]) {
   return props[key](val, quer);
}
```

But it probably should read something like:

```js
if (props[key]) {
    return props[key](coerceData(key, val), quer);
}
````

So that the `var` variable is actually cleaned up properly.

**Comment by fnky** [comment]
Why hasn't this been pushed to master? The bug is still there.

**Comment by karvapallo** [comment]
I think the version number just hasn't been bumped (and updated to npm). But you can get the bleeding edge version by doing an npm install straight from the github repo (npm install git+https://github.com/reponame)

-

Aapo Kuuselo 
aapo.kuuselo@gmail.com 
+1 (469) 999-2590

**Comment by OmgImAlexis** [comment]
This bug is still in the latest npm version. This really needs to be pushed.

**Comment by matheo** [comment]
Facing the same issue on 0.2.5 :(

**Comment by baugarten** [comment]
Published another version, 0.2.6, which contains the fix
